### PR TITLE
Revised Disclaimer

### PR DESCRIPTION
**Pull request by God-damnit-all**
I've revised the Disclaimer about Nick Walton to be more clear and concise. For legal purposes, I do not personally endorse or condone the claims alleged.

### CODE REVIEW

**Review by machiavel23 — CHANGES_REQUESTED** [review]
I can't argue it is well better structured than we could do. if you could remove the 404 parenthesis near the agpl mention of the colab and put links on

Exhibit A & Exhibit B: Datasets he used for the AI model

I  think i'll be ok to merge. I'll let Kornilov review it before of course, but with those 2 changes it'll be ok for me.

Thanks a lot for the help

**Comment by God-damnit-all** [comment]
> put links on Exhibit A & Exhibit B: Datasets he used for the AI model

Oops. That's just something I forgot to go back to when editing.

> if you could remove the 404 parenthesis near the agpl mention of the colab 

Sorry, I don't understand what this means. None of the links go to a 404 page.

_(Ignore the close/reopen below, misclick.)_

**Comment by machiavel23** [comment]
it's this

This colab is a frontend aiming to allow users to easily run different versions of AIDungeon 2. It is under AGPL (404 until merge)

to this

This colab is a frontend aiming to allow users to easily run different versions of AIDungeon 2. It is under AGPL

just remove the (404 until merge)

**Comment by God-damnit-all** [comment]
Aha. I missed that.

**Comment by God-damnit-all** [comment]
Wait. That's not even something my commit touches.

Eh, whatever.

**Comment by God-damnit-all** [comment]
Done.

**Review by machiavel23 — APPROVED** [review]
Thanks. Sorry to bother you with that little parenthesis, we should have done it before merging, so i take the chance of this pull to make it happen, because i quite lack of time for that now. I'm approving, but Kornilov will also have to check if the changes are ok for him before the pull. Thanks for the help !

**Comment by VBPXKSMI** [comment]
I approve, the changes seems less direct but still on point, good job. We still need some links for the "Beta texts" though.

**Comment by God-damnit-all** [comment]
If, at any point, you decide you want to switch back to the MIT license (which I strongly encourage), I grant advance permission to release this commit from the AGPL and for it to be used under the same MIT license.

**Comment by VBPXKSMI** [comment]
Thank you very much for everything.

**Pull request merged**
